#!/usr/bin/env ruby

require './Post'
require './test/sample'
require 'sequel'

DB = Sequel.postgres('sudovim', :user => 'sudovim', :password => 'sudovim', :host => 'localhost').run "DELETE FROM posts"

describe Post do
  before :all do
    @data = Sample.load
  end


  describe '#new' do

    it 'creates twenty entries' do
      @data.each do |entry|
        expect(Post.new title: entry[:title], content: entry[:content]).to be >= 1
      end
      expect(Post.all(length:100).length).to be == @data.length
    end

  end


  describe '#list' do

    it 'lists ten values' do
      expect(Post.list.length).to eq 10
    end

    it 'has the first entry date as 1-1-13' do
      expect(Post.list[0]['date']).to eq @data[@data.length-1][:date]
    end

    it 'has the last entry title as "Title ten"' do
      expect(Post.list[9]['title']).to eq @data[@data.length-10][:title]
    end

    it 'paginates' do
      expect(Post.list(paginate: 10).length).to eq 10
    end

    it 'paginates correctly' do
      expect(Post.list(paginate: 10)[0]['date']).to eq @data[@data.length-11][:date]
      expect(Post.list(paginate: 10)[0]['title']).to eq @data[@data.length-11][:title]
      expect(Post.list(paginate: 20)[0]['title']).to eq @data[@data.length-21][:title]
    end

  end

  describe '#find' do

    it 'gets the values for a single post' do
      data = @data[15]
      slug = Post.slugify data[:title]
      post = Post.find slug.chop
      expect(post['title']).to eq data[:title]
      expect(post['content']).to eq data[:content]
      expect(post['date']).to eq data[:date]
    end

  end

end

