#!/usr/bin/env ruby

require './Post'

describe Post do
  before :all do
    require 'redis'
    @redis = Redis.new
    @redis.flushall
    @data = [
      {:title => 'Title one',        :date => '1-1-13',  :content => '1 lorem ipsum stuff jfdsjkfjk jkd kjskjf kjf djklsld jklfdsjl lj'},
      {:title => 'Title two',        :date => '2-1-13',  :content => '2 loem ipsum stuff'},
      {:title => 'Title three',      :date => '3-1-13',  :content => '3 lrem ipsum stuff'},
      {:title => 'Title four',       :date => '4-1-13',  :content => '4 lorm ipsum stuff'},
      {:title => 'Title five',       :date => '5-1-13',  :content => '5 lorem ipsum stuff'},
      {:title => 'Title six',        :date => '5-1-13',  :content => '6 lore ipsum stuff'},
      {:title => 'Title seven',      :date => '6-1-13',  :content => '7 lorem ipsum stuff'},
      {:title => 'Title eight',      :date => '7-1-13',  :content => '8 lorem ipsum stuff'},
      {:title => 'Title nine',       :date => '8-1-13',  :content => '9 lorempsum stuff'},
      {:title => 'Title ten',        :date => '9-1-13',  :content => '10 lorem psum stuff'},
      {:title => 'Title eleven',     :date => '9-1-13',  :content => '11 lorem isum stuff'},
      {:title => 'Title twelve',     :date => '10-1-13', :content => '12 loremipum stuff'},
      {:title => 'Title thirteen',   :date => '10-1-13', :content => '13 lorem ps stuff'},
      {:title => 'Title fourteen',   :date => '10-1-13', :content => '14 lorem isum stuff'},
      {:title => 'Fifteen title',    :date => '10-1-13', :content => '15 lorem ipumstuff'},
      {:title => 'Sixteen title',    :date => '10-1-13', :content => '16 lorem ipsm tuff'},
      {:title => 'Seventeen title',  :date => '11-1-13', :content => '17 lorem ipsum suff'},
      {:title => 'Eighteen title',   :date => '11-1-13', :content => '18 lorem ipsumstuff'},
      {:title => 'Nineteen title',   :date => '11-1-13', :content => '19 lorem ipsum ff'},
      {:title => 'Twenty title',     :date => '12-1-13', :content => '20 lorem ipsum suff'},
      {:title => 'Twenty One title', :date => '12-1-13', :content => '21 lorem ipsum suff kjfd kjfd jkfd jkfd jkfd jkdf kj fkj kjdf kj'}
    ]
    @slug = 'title-one'
    @postslist = 'post::list'
  end


  describe '#slugify' do

    it 'creates a proper slug' do
      expect(Post.slugify @data[0][:title]).to eq @slug
    end

    it 'enumerates duplicates' do
      @redis.flushall
      @redis.hset Post.slugify(@data[0][:title]), 'title', @data[0][:title]
      expect(Post.slugify @data[0][:title]).to eq @slug+'1'
      @redis.flushall
    end

  end


  describe '#new' do

    it 'creates twenty entries' do
      @data.each do |entry|
        expect(Post.new entry).to be >= 1
      end
      expect(@redis.llen @postslist).to be == 21
    end

  end


  describe '#list' do

    it 'lists ten values' do
      expect(Post.list.length).to eq 10
    end

    it 'has the first entry date as 1-1-13' do
      expect(Post.list[0]['date']).to eq @data[@data.length-1][:date]
    end

    it 'has the last entry title as "Title ten"' do
      expect(Post.list[9]['title']).to eq @data[@data.length-10][:title]
    end

    it 'paginates' do
      expect(Post.list(paginate: 10).length).to eq 10
    end

    it 'paginates correctly' do
      expect(Post.list(paginate: 10)[0]['date']).to eq @data[@data.length-11][:date]
      expect(Post.list(paginate: 10)[0]['title']).to eq @data[@data.length-11][:title]
      expect(Post.list(paginate: 20)[0]['title']).to eq @data[@data.length-21][:title]
    end

  end

  describe '#find' do

    it 'gets the values for a single post' do
      data = @data[15]
      slug = Post.slugify data[:title]
      post = Post.find slug.chop
      expect(post['title']).to eq data[:title]
      expect(post['content']).to eq data[:content]
      expect(post['date']).to eq data[:date]
    end

  end

end

